name: Node.js Package

on:
  workflow_dispatch:

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Minify shell scripts and move to dist
        run: |
          mkdir -p dist
          find src -name "*.sh" -type f -exec sh -c '
            for file do
              sed -e "/^\s*#/d; /^\s*$/d; s/[[:space:]]\+/ /g; s/^[[:space:]]*//; s/[[:space:]]*$//" "$file" > "dist/$(basename "$file")"
            done
          ' sh {} +

      - name: Remove src folder
        run: rm -rf src

      - name: Publish to npm
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm_token }}
